[http]
addr = "127.0.0.1:3000"

[logger]
log_level = "debug"
log_type = "single"
log_name = "storage/logs/logs.log"
log_max_backup = 5
log_max_age = 30
log_compress = false


[app]
env = "dev"

[paging]
perpage = 10                    # 默认每页条数
url_query_page = "page"         # URL 中用以分辨多少页的参数 此值若修改需一并修改请求验证规则
url_query_sort = "sort"         # URL 中用以分辨排序的参数（使用 id 或者其他） 此值若修改需一并修改请求验证规则
url_query_order = "order"       # URL 中用以分辨排序规则的参数（辨别是正序还是倒序） 此值若修改需一并修改请求验证规则
url_query_per_page = "per_page" # URL 中用以分辨每页条数的参数 此值若修改需一并修改请求验证规则

[mysql]
db_host = "127.0.0.1"
db_port = 3306
db_database = "yxxxxxx"
db_username = "rxxx"
db_password = "sxxxx"
db_max_idle_connections = 100
db_max_open_connections = 25
db_max_life_seconds = 300

[sqlite]
db_sql_file = "database/database.db"
